spring:
  main:
    banner-mode: "OFF"
  output:
    ansi:
      enabled: DETECT
  datasource:
    url: "jdbc:h2:file:./db/orquest-test"
    username: "sa"
    password:
    driverClassName: "org.h2.Driver"
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: "classpath:db/migration"

logging:
  level:
    root: INFO
    orquest.infrastructure.configuration: DEBUG
  file:
    name: "log/orquest-test.log"
  logback:
    rollingpolicy:
      total-size-cap: 4 GB
      max-file-size: 100 MB
      max-history: 7

server:
  port: 8082

endpoint:
  status:
    path: "/status"

  v1:
    path: "/v1"
    clockin:
      path:
        base: "${endpoint.v1.path}/clockin"
        by-employee-id: "${endpoint.v1.clockin.path.base}/employee/{employee_id}"